name: Build project

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: enter the folder src
        run: cd src
      
      - name: Restore dependencies
        run: dotnet restore src/prova.sln

      - name: Build
        run: dotnet build src/prova/prova.csproj
