name: Docker Build and Push

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar a versão da tag
        id: set_tag
        run: |
          TAG=$(date +%Y%m%d%H%M)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Build da imagem Docker
        run: |
          cd src
          docker build -t nautica2025/prova01-yan:latest .
          docker tag nautica2025/prova01-yan:latest nautica2025/prova01-yan:${{ env.TAG }}

      - name: Push da imagem para o Docker Hub
        run: |
          docker push nautica2025/prova01-yan:latest
          docker push nautica2025/prova01-yan:${{ env.TAG }}
